#!/bin/bash

# Script should run checks on localhost code base
# before code changes would be committed into the repository.
# It checks if commit message matches company's commit message requirements.
#
# Commit message rules described in ./documentation/COMMIT_RULES.md

TEMPLATE="^(Fix|Update|Breaking|Docs|Build|New|Upgrade)\:\s(.*?)\s\((task|refs|fixes)\s\#(\w+)\)$"
ISCORRECT=$(cat $1 | grep -oP "$TEMPLATE" | wc -l)

if [ "$ISCORRECT" -eq 0 ]
then
  echo -en "\033[0;31m"
  cat <<\EOF
  COMMIT MSG ERROR:
  > Please, correct the message and try commit files again.
  > Commit message summaries must follow this basic format:
      Tag: Message (task #1234)

  > Example:
      Build: Update Travis to only test Node 0.10 (task #734)
      Fix: Semi rule incorrectly flagging extra semicolon (task #840)
      Upgrade: Esprima to 1.2, switch to using Esprima (task #730)
EOF
  echo -en "\033[0m"

  exit 1
else
  exit 0
fi