#!/bin/bash

# Script should run checks on localhost code base
# before code changes would be committed into the repository

# check code errors before commit
echo " "
echo "> Checking code base against code style rules..."

npm run lint

retVal=$?

if [ $retVal -ne 0 ]; then
  echo " "
  echo "^^^"
  echo "See above any issue with code style"

  exit $retVal
fi

# test code functionality before commit
echo " "
echo "> Running unit tests..."

npm test

retVal=$?

if [ $retVal -ne 0 ]; then
  echo " "
  echo "^^^"
  echo "See above any issue with unit tests"

  exit $retVal
fi