language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm install
  - npm run build
  - cat ./reports/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
on:
  branch: master